// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using BillingService.Infrastructure.Persistence;

#nullable disable

namespace BillingService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BillingDbContext))]
    partial class BillingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0")
                        .HasAnnotation("Relational:MaxIdentifierLength", 63);
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BillingService.Domain.Entities.Bill", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedNever().HasColumnType("uuid");
                b.Property<Guid>("AppointmentId").HasColumnType("uuid");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<DateTime?>("IssuedAt").HasColumnType("timestamp with time zone");
                b.Property<Guid>("PatientId").HasColumnType("uuid");
                b.Property<DateTime?>("PaidAt").HasColumnType("timestamp with time zone");
                b.Property<string>("Status").IsRequired().HasColumnType("text");
                b.Property<decimal>("TotalAmount").HasColumnType("decimal(18,2)");
                b.HasKey("Id");
                b.HasIndex("PatientId");
                b.HasIndex("AppointmentId").IsUnique();
                b.ToTable("Bills");
            });

            modelBuilder.Entity("BillingService.Domain.Entities.BillLineItem", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedNever().HasColumnType("uuid");
                b.Property<decimal>("Amount").HasColumnType("decimal(18,2)");
                b.Property<Guid>("BillId").HasColumnType("uuid");
                b.Property<string>("Description").IsRequired().HasMaxLength(500).HasColumnType("character varying(500)");
                b.Property<int>("Quantity").HasColumnType("integer");
                b.Property<decimal>("UnitPrice").HasColumnType("decimal(18,2)");
                b.HasKey("Id");
                b.HasIndex("BillId");
                b.ToTable("BillLineItems");
            });

            modelBuilder.Entity("BillingService.Domain.Entities.ServiceTariff", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedNever().HasColumnType("uuid");
                b.Property<string>("Category").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("Description").HasMaxLength(500).HasColumnType("character varying(500)");
                b.Property<bool>("IsActive").HasColumnType("boolean");
                b.Property<decimal>("Price").HasColumnType("decimal(18,2)");
                b.Property<string>("ServiceName").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                b.Property<DateTime?>("UpdatedAt").HasColumnType("timestamp with time zone");
                b.HasKey("Id");
                b.HasIndex("Category", "ServiceName");
                b.ToTable("ServiceTariffs");
                b.HasData(new
                {
                    Id = new Guid("b0000000-0000-0000-0000-000000000001"),
                    ServiceName = "Biaya Konsultasi Umum",
                    Category = "Consultation",
                    Price = 150_000m,
                    Description = (string)null,
                    IsActive = true,
                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                    UpdatedAt = (DateTime?)null,
                });
            });

            modelBuilder.Entity("BillingService.Domain.Entities.Bill", b =>
            {
                b.HasMany("BillingService.Domain.Entities.BillLineItem", "LineItems")
                 .WithOne()
                 .HasForeignKey("BillId")
                 .OnDelete(DeleteBehavior.Cascade)
                 .IsRequired();
                b.Navigation("LineItems");
            });

            modelBuilder.Entity("BillingService.Domain.Entities.BillLineItem", b =>
            {
                b.HasOne("BillingService.Domain.Entities.Bill", null)
                 .WithMany("LineItems")
                 .HasForeignKey("BillId")
                 .OnDelete(DeleteBehavior.Cascade)
                 .IsRequired();
            });
#pragma warning restore 612, 618
        }
    }
}
