apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
  namespace: careops
data:
  ASPNETCORE_ENVIRONMENT: Production
  RabbitMQ__Host: rabbitmq
  RabbitMQ__Username: guest
  RabbitMQ__Password: guest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: careops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: ghcr.io/hasankhairullahdev/careops/notification-service:latest
          ports:
            - containerPort: 5005
          envFrom:
            - configMapRef:
                name: notification-service-config
          env:
            - name: Urls
              value: "http://+:5005"
          readinessProbe:
            httpGet:
              path: /health
              port: 5005
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: careops
spec:
  selector:
    app: notification-service
  ports:
    - port: 5005
      targetPort: 5005
